### ISSUE TITLE
Build error Note.hs:21:7:

### ISSUE THREAD

**Issue by jdees** [jhedev/bahn#4]
I have the following error during build on my system after running `stack build`: [1].
Unfortunately I don't know enough haskell to know what is going on - can you help me?

Regards,
Jonathan

[1]:

```
cat bahn-0.1.0.0.log
Configuring bahn-0.1.0.0...
Preprocessing library bahn-0.1.0.0...
[ 1 of 26] Compiling Web.Bahn.Model.StopLocation ( lib/Web/Bahn/Model/StopLocation.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Web/Bahn/Model/StopLocation.o )
[ 2 of 26] Compiling Web.Bahn.Model.Note ( lib/Web/Bahn/Model/Note.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Web/Bahn/Model/Note.o )

lib/Web/Bahn/Model/Note.hs:21:7:
    parse error on input ‘$’
    Perhaps you intended to use TemplateHaskell
```

**Comment by jhedev** [comment]
Thanks for your report!

Currently, the project isn't buildable. This is due to a bug in the swagger code generator I used (I reported it here swagger-api/swagger-codegen#2319). But there has been some work on a new code generator for haskell (see swagger-api/swagger-codegen#2322) which should generate working code. 

I'll regenerate the project and update as soon as possible.

**Comment by jhedev** [comment]
The latest commit ef33c0e46cf5f71a9a2103f453661d238087a31a should fix this problem and make the project buildable again. 

Could you try again?

**Comment by jdees** [comment]
I tried again and now it builds - thanks for the fast response!

So this has been solved :).

Now a different issue (don't know if I should open a separate issue for it):

```
> "Köln Hbf" "Aachen Hbf"
Fetching results...........
Date | Departure | Prognosis | Duration | Changes | Products
>
```

so it does not return something.
Funny enough it makes a difference which Bahnhoefe I put there. So non-existing Bahnhoefe are faster processed => this looks like the calls against bahn.de succeed but later nothings is printed out.
Can I help somehow with more information for debugging?

**Comment by jhedev** [comment]
Thanks for finding this problem.

At the time I created the `bahn-cli` tool there was no public "Fahrplan API". So I kind of reverse engineered what is happening when you fill out the online form. So currently the tool just generates the correct URL and parses the HTML it gets back. 
For example, the search for "Aachen" to "Düren" yields this URL: http://reiseauskunft.bahn.de/bin/query.exe/dn?Z=Aachen&S=D%c3%bcren&start=1

Unfortunately, they recently redesigned their site which changes a few CSS classes and thus broke the tool... This should be fixed now.

However, I plan to make use of the proper API in the future (see #3 ).

**Comment by jhedev** [comment]
Maybe you can try again? Just to make sure it works :D

**Comment by jdees** [comment]
I tried again and it works like a charm :+1: 

```
$ bahn Berlin Muenchen
Fetching results..............
Departure | Prognosis | Duration | Changes | Products
18:27 |  | 6:14 | 0 | ICE
19:35 | +0 | 10:27 | 2 | ICE
19:49 |  | 10:56 | 2 | ICE, IC, RE
19:49 |  | 11:21 | 1 | ICE, CNL
19:49 |  | 11:21 | 1 | ICE, IC
```

I also saw that they just (recently) made public access to their APIs. Programming against that is probably much simpler/relyable.

Anyhow I will make this now my default program to check for trains.
I will also open some feature request and test it further if you need a tester :).

=> you can close this issue as it is solved

**Comment by jhedev** [comment]
Wow, glad to hear that :)

That's a good motivation to get the tool in better shape!
